first pass at autopilot cmd
glifio/cli pull request #69
Opened 2023-06-09 08:03 UTC by lanzafame

2023-06-13 23:10 UTC, Schwartz10 requested changes
Overall looks good, small changes requested

2023-06-13 23:10 UTC, Schwartz10 commented on cmd/agent_autopilot.go
> +				epochFreq := big.NewFloat(float64(frequency * 24 * 60 * 60 / 30))
Should be able to use https://github.com/glifio/go-pools/blob/bcdd3dac557e3e049979532ee55c19d643b34f84/constants/constants.go#L16 here

2023-06-14 01:26 UTC, lanzafame commented on cmd/agent_autopilot.go
> +				frequency := viper.GetFloat64("autopilot.frequency")
Correct.

2023-06-14 01:27 UTC, lanzafame commented on cmd/agent_autopilot.go
> +					args = append(args, fmt.Sprintf("%d", amount))
Yes, I will fix that.

2023-06-14 01:27 UTC, lanzafame commented on cmd/agent_autopilot.go
> +				if paymentType == "principal" || paymentType == "custom" {
I just hit this issue. So yes I will implement this now.

2023-06-19 06:05 UTC, lanzafame commented on config.toml
> +payment-type = 'to-current'
```suggestion
# <to-current|principal|custom>
payment-type = 'to-current'
```

2023-06-20 00:02 UTC, merged